name: ElixirXDR CI

on:
  push:
    branches:
      - main
      - 'v*.[0-9]'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['22.3']
        elixir: ['1.10', '1.11']
    env:
      MIX_ENV: test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            coveralls.io:443
            github.com:443
            repo.hex.pm:443
            builds.hex.pm:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install Dependencies
        run: |
          rm -rf deps _build
          mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run credo
        run: mix credo --strict
      - name: Run Tests and Excoveralls
        run: mix coveralls.github --parallel --flagname otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            coveralls.io:443

      - name: Set BUILD_NUMBER for Pull Request event
        if: github.event_name == 'pull_request'
        run: echo "BUILD_NUMBER=${{ github.event.pull_request.head.sha }}-PR-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Set BUILD_NUMBER for Push event
        if: github.event_name == 'push'
        run: echo "BUILD_NUMBER=${{ github.sha }}" >> $GITHUB_ENV
      - name: Publish Coverage Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        run: |
          curl -k "https://coveralls.io/webhook" -d "repo_token=$GITHUB_TOKEN&repo_name=$GITHUB_REPOSITORY&payload[build_num]=$BUILD_NUMBER&payload[status]=done"
